### ISSUE TITLE
[Feature Request] Container start line storage

### ISSUE THREAD

**Issue by thesugarat** [SelfhostedPro/Yacht#112] opened 2020-09-25 03:11 UTC
I would like to see a basic way to store and display text. The docker start lines that I edit and use to create containers should be storable. For example is the start line for Yacht:  

docker run -d -p 8321:8000 -v /var/run/docker.sock:/var/run/docker.sock -v yacht:/config selfhostedpro/yacht

I've edited the port information, and in another I could edit the volume information...  I want to be able to store this text information inside the docker volume "yacht" (or bind mount) so that the info survives restarts and container updates. Preferably an interface where you can name each file and have a set number of characters for the "sheet"/notes. And be able to copy and paste from it.

**Comment by SelfhostedPro** [comment] 2020-09-25 03:38
You may be able to store this in a label if you're just looking for text storage. That feature will be pushed out to the devel branch in the next hour or so if you'd like to try it out.

**Comment by SelfhostedPro** [comment] 2020-09-25 04:22
Duplicate of #113 going to merge this with it and close this one out.

**Closed by SelfhostedPro** 2020-09-25 04:22 UTC
