### ISSUE TITLE
No Projects Displaying After Incorrectly Formatter File Saved

### ISSUE THREAD

**Issue by bm751613** [SelfhostedPro/Yacht#369] opened 2021-04-12 18:16 UTC
When creating a new project I created a file that had everything under the initial version declaration indented too far. The file saved but caused the "Internal Server Error: undefined" and would no longer display any existing projects. I removed the indent and everything went back to normal.

File Causing Issue:
![image](https://user-images.githubusercontent.com/7523158/114441665-ab3aef80-9b99-11eb-8fce-6e2f2c238d91.png)

Corrected File:
![image](https://user-images.githubusercontent.com/7523158/114441715-baba3880-9b99-11eb-909b-5caea5d485b3.png)

**Comment by SelfhostedPro** [comment] 2021-04-12 18:39
Would you be willing to try the :devel tag to see if it's resolved there. I believe there was another similar issue that I resolved.

**Comment by bm751613** [comment] 2021-04-12 18:56
I am currently on devel. I also tried reverting to latest and back with no luck.

**Comment by SelfhostedPro** [comment] 2021-04-12 19:06
Which version of devel are you on? (Should say at the bottom of the settings page)

**Comment by SelfhostedPro** [comment] 2021-04-12 19:10
Just to show that it's working correctly on the latest devel version:
![yacht-projects-malformed](https://user-images.githubusercontent.com/66331933/114448084-f64c0700-9b87-11eb-849d-0e935e97aff3.gif)

**Comment by bm751613** [comment] 2021-04-12 19:20
Im on devel-2021-04-09--15

I just tried again, projects working, as soon as I tab them over and save it errors our. A page refresh shows no projects, and logging into my VPS I can see that the tab saved. Removing it locally and refreshing the page brings everything back.

![image](https://user-images.githubusercontent.com/7523158/114448866-1688bf80-9ba2-11eb-8c26-7602d85768f2.png)
![image](https://user-images.githubusercontent.com/7523158/114448949-30c29d80-9ba2-11eb-8241-87dcda77269d.png)
![image](https://user-images.githubusercontent.com/7523158/114449155-6e272b00-9ba2-11eb-8b7b-4da1e1ef80b4.png)

**Comment by SelfhostedPro** [comment] 2021-04-12 19:34
hmmm. I haven't made any changes since that version to this process but it won't let me save due to the yaml  being invalid if I have it indented like yours. 
![yacht-projects-malformed](https://user-images.githubusercontent.com/66331933/114450549-00233980-9b8b-11eb-85e1-21cc8e9a76b0.gif)

Can you send me the support bundle for your container? It should be accessible on the App Details page for your Yacht container (help button). (please extract and take a look to make sure no personally identifiable info is in the .zip)
![image](https://user-images.githubusercontent.com/66331933/114450730-3a8cd680-9b8b-11eb-81c4-40d7f6266d47.png)

**Comment by bm751613** [comment] 2021-04-12 19:53
My guess is that after I indent it throws the error, but is actually saves to disk. Then I can not change it back because the file is invalid and the projects are not being read at all.

[yacht_bundle.zip](https://github.com/SelfhostedPro/Yacht/files/6299438/yacht_bundle.zip)

**Comment by SelfhostedPro** [comment] 2021-04-12 20:00
It does look like it should have failed writing to disk at the first server error. I'll do some more digging and see if I can sort it out. You should manually be able to add /edit to the end of the URL where you would see the projects details as a workaround to modify that file in the meantime.

**Comment by SteveDinn** [comment] 2021-05-18 12:31
I've noticed this happen when I've edited the file to be valid YAML, but just not valid docker-compose YAML. I was trying to rename a container and accidentally left two labels, like this:
```
version: "3"
services:
  accidentally_left:
  yacht:
    image: selfhostedpro/yacht
    container_name: yacht
    hostname: yacht
    restart: always
    ports:
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/config
```

So `accidentally_left` is valid YAML, but doesn't represent a proper docker-compose instance, and I was left in the same state. Editing the project's `docker-compose.yml` brought it back.

**Comment by akujinnoninjin** [comment] 2021-05-19 14:27
This behavior seems to occur for **any** 'invalid' project file, testing in v0.0.7-alpha-2021-05-07--12.

To reproduce: Create a new project, give it a name (`Test`), and then enter _any_ text in the template field (eg `TestTestTest`). On submitting, the "internal server error: undefined" occurs, and the projects page displays empty.

Manually returning to the edit uri after leaving it (ie. 'projects/test/edit') shows a blank project. A solution is to edit/delete the offending YAML file from '/var/lib/docker/volumes/yacht/_data/compose/'.

**Comment by SelfhostedPro** [comment] 2021-05-28 00:35
Latest devel build will give useful feedback whenever there's an error in the yaml. If any of you get a chance to test and report back here it would be appreciated.

**Comment by SelfhostedPro** [comment] 2021-05-31 16:27
Fix has been published to the latest release. If there are any issues with it, comment here and I'll reopen.

**Closed by SelfhostedPro** 2021-05-31 16:27 UTC
