### ISSUE TITLE
Issue with Yacht dashboard - Exceeding the max Dokcer count - I think.

### ISSUE THREAD

**Issue by aryehassbian** [SelfhostedPro/Yacht#145] opened 2020-10-04 19:30 UTC
Hi, 
I have been using Yacht for the last couple of days. Everything works OK till I added a couple of Dockers too many.
At this point I can NOT see anything in the Dashboard BUT the word Status and a Refresh Arrow.
Doing F12 - Getting this Error:
```
Error: Request failed with status code 401
    at t.exports (createError.js:16)
    at t.exports (settle.js:17)
    at XMLHttpRequest.f.onreadystatechange (xhr.js:69)
Home.vue:85 Starting connection to Websocket
```
Not sure what type of Authorization is needed and How I am violating it?
Please assist.
Thanks

**Comment by SelfhostedPro** [comment] 2020-10-04 19:46
Duplicate of #144

**Closed by SelfhostedPro** 2020-10-04 19:46 UTC
